export interface dataPersonaResponse{
    codigoError: string,
    mensajeError: string,
    firmaBase64: string,
    fotoBase64: string,
    longitudFirma: string,
    longitudFoto: string,
    huellaDerechaBase64: string,
    huellaIzquierdaBase64: string,
    longitudHuellaDerecha: string,
    longitudHuellaIzquierda: string,
    mostrarDatos: string,
    persona: personaConsultaDatos,
    subtipoConsulta: string
}

export interface personaConsultaDatos{
    codigoError: string,
    mensajeError: string,
    apellidoMaternoCasadaDeclarante: string,
    apellidoMaternoCasadaResponsable: string,
    apellidoMaternoConuyugeCasada: string,
    apellidoMaternoConyuge: string,
    apellidoMaternoDeclarante: string,
    apellidoMaternoResponsable: string,
    apellidoPaternoConyuge: string,
    apellidoPaternoDeclarante: string,
    apellidoPaternoResponsable: string,
    blockChalet: string,
    codigoDeclarante: string,
    codigoPostal: string,
    codigoRestriccion: string,
    codigoVinculo: string,
    datosAdicionales: datosAdicionalesGetConsultaDatos,
    datosBasicos: datosBasicosGetConsultaDatos,
    datosDomicilio: datosDomicilioGetConsultaDatos,
    datosNacimiento: datosNacimientoGetConsultaDatos,
    descripcionCodigoDeclarante: string,
    descripcionDiscapacidad: string,
    descripcionIndicadorGrupoRestriccion: string,
    descripcionInterdiccion: string,
    descripcionPrefijoBlockChalet: string,
    descripcionPrefijoDireccion: string,
    descripcionPrefijoDpto: string,
    descripcionPrefijoUrb: string,
    descripcionRestriccion: string,
    descripcionTipoFichaRegistral: string,
    descripcionVinculo: string,
    direccion: string,
    discapacidad: string,
    etapa: string,
    indicadorGrupoRestriccion: string,
    interdiccion: string,
    interior: string,
    lote: string,
    manzana: string,
    nombreConyuge: string,
    nombreDeclarante: string,
    nombreResponsable: string,
    numDireccion: string,
    numDocResponsable: string,
    numDocumentoConyuge: string,
    numDocumentoDeclarante: string,
    prefijoBlockChalet: string,
    prefijoDireccion: string,
    prefijoDpto: string,
    prefijoUrb: string,
    tipoDocResponsable: string,
    tipoDocumentoConyuge: string,
    tipoDocumentoDeclarante: string,
    tipoFichaRegistral: string,
    urbzanizacion: string
}
export interface datosAdicionalesGetConsultaDatos{
    anhoEstudio: string,
    codigoCaducidad: string,
    codigoEstadoCivil: string,
    codigoGradoInstruccion: string,
    codigoSexo: string,
    constaciaSufragio: string,
    descripcionCaducidad: string,
    descripcionConstaciaSufragio: string,
    descripcionDocumentoSustentatorio: string,
    descripcionEstadoCivil: string,
    descripcionGradoInstruccion: string,
    descripcionSexo: string,
    estatura: string,
    fechaExpedicion: string,
    fechaFallecimiento: string,
    fechaInscripcion: string,
    numeroDocumentoSustentatorio: string,
    tipoDocumentoSustentatorio: string
}
export interface datosBasicosGetConsultaDatos{
    apellidoCasada: string,
    apellidoMaterno: string,
    apellidoPaterno: string,
    caracterVerificacion: string,
    nombres: string,
    numeroDni: string,
    tipoDocumento: string
}
export interface datosDomicilioGetConsultaDatos{
    codigoUbigeoContinenteDomicilio: string,
    codigoUbigeoDepartamento: string,
    codigoUbigeoDistrito: string,
    codigoUbigeoLocalidad: string,
    codigoUbigeoPaisDomicilio: string,
    codigoUbigeoProvincia: string,
    continenteDomicilio: string,
    departamento: string,
    direccion: string,
    distrito: string,
    localidad: string,
    paisDomicilio: string,
    provincia: string
}
export interface datosNacimientoGetConsultaDatos{
    apellidoMaternoCasadaMadre: string,
    apellidoMaternoMadre: string,
    apellidoMaternoPadre: string,
    apellidoPaternoMadre: string,
    apellidoPaternoPadre: string,
    codigoUbigeoContinenteNacimiento: string,
    codigoUbigeoDepartamento: string,
    codigoUbigeoDistrito: string,
    codigoUbigeoLocalidad: string,
    codigoUbigeoPaisNacimiento: string,
    codigoUbigeoProvincia: string,
    continenteNacimiento: string,
    departamento: string,
    descripcionTipoDocumento: string,
    distrito: string,
    fechaNacimiento: string,
    localidad: string,
    nombreMadre: string,
    nombrePadre: string,
    numDocumentoMadre: string,
    numDocumentoPadre: string,
    paisNacimiento: string,
    provincia: string,
    tipoDocumentoMadre: string,
    tipoDocumentoPadre: string
}

export interface dataSeguro{
    TIPO_ASEGURADO:string,
    GENERO: string,
    DIRECCION_ASEGURADO: string,
    DGACAUT: string,
    DGATAPA: string,
    DGATAMA: string,
    DGATPNO: string,
    DGATSNO: string,
    DGANDID: string,
    DGAFNAC: string,
    DGAFFAL: string,
    DGACTAS: string,
    DGAFVDE: string,
    DGAFVHA: string,
    NOM_CAS_ADSCRIPCION: string,
    NOM_RED_ADSCRIPCION: string,
    DPTO_ASEGURADO: string,
    PROV_ASEGURADO: string,
    DIST_ASEGURADO: string,
    CONDICION: string,
    DESC_DGACTAT: string,
    CORREO: string,
    TELEFONO_FIJO: string,
    CELULAR: string,
    ID_CIUDADANO: string
}

export interface AcreditarFichaPostulante{
    tipoDoc: string,
    numDoc: string,
    idUnidadOpe: string
}
